services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: rds.c1oigkqq4mak.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: seu-usuario
      WORDPRESS_DB_PASSWORD: sua-senha
      WORDPRESS_DB_NAME: db_my_wordpress
    volumes:
      - /wordpress:/var/www/html
    networks:
      - tunel

